config/routes.rb
Rails.application.routes.draw do
  resources :wellness_reservations
  resources :wellness_centers
  resources :restaurant_reservations
  resources :restaurants
  resources :users
   get 'users/:id/showreservations', to: 'users#showreservations', as: 'showreservations'
   post '/restaurant_reservations/new', to: 'restaurant_reservations#create'
   get '/restaurant_reservations/:id/edit', to: 'restaurant_reservations#edit'

   post '/wellness_reservations/new', to: 'wellness_reservations#create'
   get '/wellness_reservations/:id/edit', to: 'wellness_reservations#edit'

   get '/about', to: 'static#about'
   get '/assets/AdobeStock_260128861.jpeg', to: 'restaurants#index'
   get '/assets/AdobeStock_163003185.jpeg', to: 'wellnesscenter#index'
   get '/assets/Restaurant1192.mp4', to: 'users#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :restaurant_reservations
    has_many :users, through: :restaurant_reservations
end

app/models/restaurant_reservation.rb
class RestaurantReservation < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant


  validates :party_size, numericality: {
    greater_than: 0 
  }
  validates :date, numericality: {
        greater_than: 0
  }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :restaurant_reservations
    has_many :restaurants, through: :restaurant_reservations
    has_many :wellness_reservations 
    has_many :wellness_centers, through: :wellness_reservations

validates :username, presence: true
validates :username, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters!" }
validates :password, presence: true 
validates :password, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters!" }
end

app/models/wellness_center.rb
class WellnessCenter < ApplicationRecord
    has_many :wellness_reservations
    has_many :users, through: :wellness_reservations
end

app/models/wellness_reservation.rb
class WellnessReservation < ApplicationRecord
  belongs_to :user
  belongs_to :wellness_center
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurant_reservations_controller.rb
class RestaurantReservationsController < ApplicationController
    def show
        @restaurantreservation = RestaurantReservation.find(params[:id])
    end

    def new
        @restaurantreservation = RestaurantReservation.new
    end

    def create
        @restaurantreservation = RestaurantReservation.create(restaurantreservation_params)
        redirect_to showreservations_path(params[:restaurant_reservation][:user_id])
    end

    def edit      
        @restaurantreservation = RestaurantReservation.find(params[:id])    
    end

    def update        
        @restaurantreservation = RestaurantReservation.find(params[:id])        
        @restaurantreservation.update(restaurantreservation_params)  
        redirect_to showreservations_path(params[:restaurant_reservation][:user_id])    
    end 

    def destroy       
       @restaurantreservation = RestaurantReservation.find(params[:id])        
       @restaurantreservation.destroy    
       redirect_back fallback_location: showreservations_path #(@restaurantreservation)    
    end

    private

    def restaurantreservation_params
    params.require(:restaurant_reservation).permit(:restaurant_name, :party_size, :date, :time, :user_id, :restaurant_id)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    def index
        @restaurants = Restaurant.all
    end

    def show
        @restaurant = Restaurant.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def about
    end
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end

    def showreservations
        @user = User.find(params[:id])
    end

    def new 
      @user = User.new
      @errors = flash[:errors]
    end

    def create
        user = User.create(user_params)
        if user.valid?
            redirect_to user_path(user.id)
        else
            flash[:errors] = user.errors.full_messages
            redirect_to new_user_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :location)
    end
end

app/controllers/wellness_centers_controller.rb
class WellnessCentersController < ApplicationController
    def index
        @wellnesscenters = WellnessCenter.all
    end

    def show
        @wellnesscenter = WellnessCenter.find(params[:id])
    end
end

app/controllers/wellness_reservations_controller.rb
class WellnessReservationsController < ApplicationController
    def show
        @wellnessreservation = WellnessReservation.find(params[:id])
    end

    def new
        @wellnessreservation = WellnessReservation.new
    end

    def create
        @wellnessreservation = WellnessReservation.create(wellnessreservation_params)
        redirect_to showreservations_path(params[:wellness_reservation][:user_id])
    end

    def edit      
        @wellnessreservation = WellnessReservation.find(params[:id])    
    end

    def update        
        @wellnessreservation = WellnessReservation.find(params[:id])        
        @wellnessreservation.update(wellnessreservation_params)  
        redirect_to showreservations_path(params[:wellness_reservation][:user_id])    
    end 

    def destroy       
        @wellnessreservation = WellnessReservation.find(params[:id])        
        @wellnessreservation.destroy  
        redirect_back fallback_location: showreservations_path  
    end

    private

    def wellnessreservation_params
        params.require(:wellness_reservation).permit(:wellnesscenter_name, :group_size, :date, :time, :user_id, :wellness_center_id)
    end
 end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_reservations_helper.rb
module RestaurantReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wellness_centers_helper.rb
module WellnessCentersHelper
end

app/helpers/wellness_reservations_helper.rb
module WellnessReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotz</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!— NAVBAR —>
  <nav class="navbar navbar-expand navbar-light bg-blue">
  <a class="navbar-brand" href="#">Spotz</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
​
  <div class="collapse navbar-collapse" id="navbarsExample02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= restaurants_path %>">Eat<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= wellness_centers_path %>">Live</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>
    </ul>
  </div>
</nav>
<style>
head {color: ;}
* {
  font-family: "Arial";
  }
</style>

  
  <body> 
    <%= yield %>
  </body>
</html>

app/views/restaurant_reservations/_form.erb
<!DOCTYPE html>
<html>
<body style="background-color:#D5E4CE;">

<%= form_with model: @restaurantreservation, local: true do |f| %>
    <%= f.label :party_size %>   
    <%= f.number_field :party_size %> <br>    

    <%= f.label :date %>  
    <%= f.text_field :date %><br>   

    <%= f.label :time %>    
    <%= f.text_field :time %><br>

    <%= f.label :user_id %>    
    <%= f.collection_select :user_id, User.all, :id, :username %><br>

    <%= f.label :restaurant_id %>    
    <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %><br>

    <%= f.submit "Submit" %>
    <% end %>


</body>
</html>

app/views/restaurant_reservations/edit.erb
<br><br><br><br><br><br><br><br>
<center><h2>Change Reservation</h2>
 <%= render "form" %></center>

app/views/restaurant_reservations/new.erb
<center> 
<br><br><br><br><br><br><br><br>
<h2>Create Reservation</h2>
<h1><%=@restaurantreservation.restaurant_name %></h1>    
        <%= render "form" %>
        </center>

app/views/restaurants/index.erb
<%= image_tag("/assets/AdobeStock_260128861.jpeg", width: '2000px')%>

<center><br><h1>Restaurants</h1></center>
<% @restaurants.each do |restaurant|%>
<div class="container">
  <h1> </h1>
  <br>
  <div class="row">
        <div class="col-md-12" style="background-color:rgb(240, 240, 240);">
            <center><br><%= link_to restaurant.name, restaurant_path(restaurant.id) %><br></center>
            <center><%= restaurant.bio %><br><br></center>
        </div>
        
    </div>
</div>
<%end%>

    

app/views/restaurants/show.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= image_tag("/assets/AdobeStock_243483994.jpeg", width: '2000px')%>
<style>
.container {
  position: sticky;
  font-family: "Courier New";
  font-size: 150%
}

.text-block {
  position: absolute;
  bottom: 20px;
  right: 20px;
  background-color: rgba(0,0,0,0.4);
  color: white;
  padding-left: 20px;
  padding-right: 20px;
}
</style>
</head>
<body>

<div class="container"> 
    <center>
        <div class="text-block">
            <b><h1><%= @restaurant.name %></h1></b>
             <%= @restaurant.bio %><br>
             <%= @restaurant.address %><br>
             <%= @restaurant.url %><br>
             Most Recent Review: <br> "<%= @restaurant.review %>"<br>
             Rating: <%= @restaurant.avg_rating %><br>

        <%= button_to "Create a Reservation", new_restaurant_reservation_path(@restaurant), method: :get %><br></center>
        </div>
</div>


</body>
</html> 

app/views/users/index.erb
<%= video_tag "Restaurant1192.mp4", id: 'background', autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
<br><br><br><br><br><br><br>

<style>body {  color: white;}</style>

<center><h1><b>&ensp;&ensp; Welcome </h1> <br>
<center><h3><b>&ensp;&ensp;&ensp; Please log in </h3> <br>
<%= form_with model: @user, local: true do |f| %>
    <%= f.label :username %>   
    <%= f.text_field :username %> <br>    

    <%= f.label :password %>  
    <%= f.text_field :password %><br>   

    <%= f.submit "Sign in" %>
    <% end %>


<%= button_to "Sign up", new_user_path, method: :get%> </center>

app/views/users/new.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= image_tag("/assets/AdobeStock_285081303.jpeg", width: '2000px')%>
<style>
.container {
  position: absolute;
  font-family: "Courier New";
  font-size: 130%
}

.text-block {
  position: absolute;
  bottom: 20px;
  right: 20px;
  background-color: rgba(0,0,0,0.4);
  color: White;
  padding-left: 20px;
  padding-right: 20px;
}
</style>
</head>

<body>
    <% if @errors %>
        <% @errors.each do |error| %>
            <p style="color:red"><%= error %></p>
         <% end %>
    <% end %>


<div class="container"> 
    <center>
    <div class="text-block">
        <%= form_with model: @user do |f| %>
        Sign up <br>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <br>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <br>
        <%= f.label :location %>
        <%= f.text_field :location %>
        <br>

        <%= f.submit "Sign Up" %>
        <% end %>

    </div>
</div>
</body>

app/views/users/show.erb
<!DOCTYPE html>
<html>
    <head>
        <style>
        body  {
            background-image: url('/assets/AdobeStock_285081303.jpeg');
            background-attachment: fixed;
             background-position: 50% 50%; 
            }
        </style>
        </head>

<body>
    <div style="text-align:center">
    <br><br><br><br><br><br><br><br><br><br>
        <center><h1 style="color:white"> Welcome<%= + "  " +@user.username.capitalize %></h1><br><br>

            <%= button_to "Reservations", showreservations_path(@user) , method: :get%>
            <%= button_to "View Black Owned Restaurants", "/restaurants", method: :get %>
            <%= button_to "View Black Owned Wellness Centers", "/wellness_centers", method: :get%><br>

            <%= button_to "Back", users_path, method: :get%>
        </center>

    </div>
</body>

app/views/users/showreservations.erb
<center>
<h1>Restaurant Reservations</h1>

<% @user.restaurant_reservations.each do |reservation|%>

         <%= link_to reservation.restaurant.name, restaurant_path(reservation.restaurant_id) %><br>
         <%= reservation.date %><br>
         <%= reservation.time %><br><br>

         <%= link_to "Edit Reservation", edit_restaurant_reservation_path(reservation), method: :get%><br>
         <%= link_to "Delete Reservation", restaurant_reservation_path(reservation), method: :delete%><br><br><hr>
         <% end %>
         <hr>


<h1>Wellness Reservations</h1>
<% @user.wellness_reservations.each do |wellnessreservation|%>

<%= link_to wellnessreservation.wellness_center.name, wellness_center_path(wellnessreservation.wellness_center_id) %><br>
<%= wellnessreservation.date %><br>
<%= wellnessreservation.time %><br><br>

<%= link_to "Edit Reservation", edit_wellness_reservation_path(wellnessreservation), method: :get%><br>
<%= link_to "Delete Reservation", wellness_reservation_path(wellnessreservation), method: :delete%><br><br>
<% end %>

<%= link_to "Home Page", user_path(@user), method: :get%><br><br>
</center>

app/views/wellness_centers/index.erb
<%= image_tag("/assets/AdobeStock_163003185.jpeg", width: '2000px')%>

<center><br><h1>Wellness Centers</h1></center>
<% @wellnesscenters.each do |wellness_center|%>

<div class="container">
  <h1> </h1>
  <br>
    <div class="row">
      <div class="col-md-12" style="background-color:rgb(240, 240, 240);">
          <center><br><%= link_to wellness_center.name, wellness_center_path(wellness_center.id)%><br></center>
          <center><%= wellness_center.bio %><br><br></center>
        </div>
       </div>
    </div>   
<%end%>

app/views/wellness_centers/show.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= image_tag("/assets/Screen Shot 2020-07-31 at 1.41.40 AM.png", width: '2000px')%>
<style>
.container {
  position: sticky;
  font-family: "Courier New";
  font-size: 150%
}

.text-block {
  position: absolute;
  bottom: 20px;
  right: 20px;
  background-color: rgba(0,0,0,0.4);
  color: white;
  padding-left: 20px;
  padding-right: 20px;
}
</style>
</head>
<body>

<div class="container"> 
    <center>
        <div class="text-block">

            <b><h1><%= @wellnesscenter.name %></h1></b>
            <%= @wellnesscenter.bio %><br>
            <%= @wellnesscenter.address %><br>
            <%= @wellnesscenter.url %><br>
            Most Recent Review:<br><%= @wellnesscenter.review %><br>
            Rating:<%= @wellnesscenter.avg_rating %> <br><br>

<%= button_to "Create a Reservation", new_wellness_reservation_path(@wellnesscenter), method: :get %><br>

app/views/wellness_reservations/_form.erb
<!DOCTYPE html>
<html>
<body style="background-color:#D5E4CE;">

<%= form_with model: @wellnessreservation, local: true do |f| %>
    <%= f.label :group_size %>   
    <%= f.number_field :group_size %> <br>    

    <%= f.label :date %>  
    <%= f.text_field :date %><br>   

    <%= f.label :time %>    
    <%= f.text_field :time %><br>

    <%= f.label :user_id %>    
    <%= f.collection_select :user_id, User.all, :id, :username %><br>

    <%= f.label :wellnesscenter_id %>    
    <%= f.collection_select :wellness_center_id, WellnessCenter.all, :id, :name %><br>
    

    <%= f.submit "Submit" %>
    <% end %>

</body>
</html>

app/views/wellness_reservations/edit.erb
<br><br><br><br><br><br><br><br>
<center><h2>Change Reservation</h2>
 <%= render "form" %></center>

app/views/wellness_reservations/new.erb
<br><br><br><br><br><br><br><br>
<center> 
<h2>Create Reservation</h2>
<h1><%=@wellnessreservation.wellnesscenter_name %></h1>   
 <%= render "form" %>
 </center>